/**
 * Editorial seed corpus for the Question Bank.
 *
 * These records are published learning content. Answers are intentionally
 * structured for interview practice: a concise conclusion, the reasoning an
 * experienced practitioner should articulate, and practical verification.
 */
export type QuestionSeedDraft = {
  slug: string;
  title: string;
  questionBody: string;
  questionType: string;
  difficulty: number;
  role: string;
  seniority: string;
  technologies: string[];
  authority: 'CANONICAL' | 'REFERENCE' | 'FRAMEWORK';
  answerBody: string;
  explanationBody: string;
  rubric: string[];
  commonMistakes: string[];
  sourceType: string;
};

const enrichTechnicalAnswer = (title: string, coreAnswer: string, technologies: string[]) => {
  const scope = technologies.length > 0 ? ` trong bối cảnh ${technologies.join(', ')}` : '';

  return [
    `Kết luận ngắn: ${coreAnswer}`,
    '',
    'Cách trả lời ở mức chuyên gia:',
    `1. Bắt đầu từ mục tiêu và ràng buộc của ${title}${scope}: nêu điều gì cần tối ưu (độ đúng, độ trễ, chi phí, an toàn hoặc khả năng vận hành) trước khi chọn giải pháp.`,
    '2. Giải thích cơ chế và quyết định theo quan hệ nguyên nhân–hệ quả; tránh chỉ liệt kê tên công cụ hoặc thuật ngữ.',
    '3. Nêu trade-off, failure mode và điều kiện không nên áp dụng. Một câu trả lời tốt phải chỉ ra rủi ro nào được chấp nhận và cách giảm blast radius.',
    '4. Chốt bằng cách kiểm chứng trong thực tế: test phù hợp, metric/log/trace cần theo dõi, ngưỡng cảnh báo và phương án rollback hoặc khắc phục.',
    '',
    'Khi phỏng vấn, hãy thay ví dụ tổng quát bằng một quyết định bạn từng thực hiện: bối cảnh, dữ liệu quan sát được, lựa chọn đã cân nhắc và kết quả sau triển khai.',
  ].join('\n');
};

const enrichFrameworkAnswer = (coreAnswer: string) =>
  [
    `Thông điệp chính: ${coreAnswer}`,
    '',
    'Cách trình bày thuyết phục trong 60–90 giây:',
    '1. Mở bằng bối cảnh thật và vai trò của bạn, đủ cụ thể để người nghe hiểu phạm vi trách nhiệm.',
    '2. Nêu quyết định hoặc hành động cá nhân, lý do lựa chọn và cách phối hợp với những người liên quan.',
    '3. Kết quả cần có bằng chứng phù hợp: số liệu, phản hồi, mức giảm rủi ro hoặc thay đổi chất lượng; nếu không có số liệu, nói rõ cách bạn quan sát tác động.',
    '4. Kết bằng điều bạn học được và cách áp dụng vào vị trí đang ứng tuyển. Không biến câu trả lời thành lời hứa chung chung.',
    '',
    'Hãy giữ sự trung thực: dùng trải nghiệm của chính bạn, giải thích được từng số liệu và nêu rõ phần đóng góp của bản thân so với phần việc của cả nhóm.',
  ].join('\n');

const technical = (
  slug: string,
  title: string,
  questionBody: string,
  answerBody: string,
  role: string,
  seniority: string,
  technologies: string[],
  difficulty = 2,
  questionType = 'conceptual',
): QuestionSeedDraft => ({
  slug,
  title,
  questionBody,
  questionType,
  difficulty,
  role,
  seniority,
  technologies,
  authority: 'REFERENCE',
  answerBody: enrichTechnicalAnswer(title, answerBody, technologies),
  explanationBody:
    'Đáp án tham khảo cần nêu nguyên lý, các giới hạn áp dụng và cách kiểm chứng trong hệ thống thực tế. Không chấm theo việc lặp lại đúng câu chữ.',
  rubric: [
    'Nêu đúng cơ chế hoặc nguyên lý cốt lõi',
    'Liên hệ được với tác động thực tế',
    'Chỉ ra ít nhất một giới hạn, trade-off hoặc edge case',
  ],
  commonMistakes: [
    'Trả lời bằng định nghĩa nhưng không giải thích cơ chế',
    'Khẳng định một giải pháp luôn đúng cho mọi bối cảnh',
    'Bỏ qua lỗi, hiệu năng hoặc khả năng quan sát khi chúng liên quan',
  ],
  sourceType: 'official-documentation',
});

const framework = (
  slug: string,
  title: string,
  questionBody: string,
  answerBody: string,
  role: string,
  seniority: string,
  difficulty = 3,
): QuestionSeedDraft => ({
  slug,
  title,
  questionBody,
  questionType: 'behavioral',
  difficulty,
  role,
  seniority,
  technologies: [],
  authority: 'FRAMEWORK',
  answerBody: enrichFrameworkAnswer(answerBody),
  explanationBody:
    'Đây là khung trả lời đề xuất. Ứng viên cần dùng trải nghiệm thật, không bịa số liệu hoặc quy mô dự án; người phỏng vấn đánh giá bối cảnh, hành động cá nhân, kết quả và sự phản tư.',
  rubric: [
    'Bối cảnh và trách nhiệm cá nhân rõ ràng',
    'Hành động cụ thể, có lý do và cách phối hợp',
    'Kết quả có bằng chứng hoặc chỉ số phù hợp',
    'Có bài học hoặc cách làm tốt hơn cho lần sau',
  ],
  commonMistakes: [
    'Kể việc của cả nhóm nhưng không nêu đóng góp cá nhân',
    'Chỉ mô tả kết quả, thiếu quyết định và hành động',
    'Tô vẽ tác động hoặc dùng số liệu không thể giải thích',
  ],
  sourceType: 'editorial-framework',
});

type ExpansionTopic = {
  slug: string;
  title: string;
  core: string;
  role: string;
  seniority: string;
  technologies: string[];
  difficulty: number;
};

const expansionTopics: ExpansionTopic[] = [
  {
    slug: 'http-cache',
    title: 'HTTP caching',
    core: 'Phân biệt Cache-Control, freshness, validation bằng ETag/If-None-Match và khi nào response riêng tư không được cache bởi shared cache.',
    role: 'backend-engineer',
    seniority: 'mid-level',
    technologies: ['rest-api'],
    difficulty: 3,
  },
  {
    slug: 'cors',
    title: 'CORS',
    core: 'CORS là cơ chế do browser thực thi; server phải whitelist origin/method/header cần thiết, không dùng wildcard với credential và hiểu preflight OPTIONS.',
    role: 'frontend-engineer',
    seniority: 'mid-level',
    technologies: ['rest-api'],
    difficulty: 3,
  },
  {
    slug: 'oauth-oidc',
    title: 'OAuth 2.0 và OpenID Connect',
    core: 'OAuth 2.0 ủy quyền truy cập; OpenID Connect bổ sung identity. Chọn flow phù hợp, validate issuer/audience/expiry, dùng PKCE cho public client và không coi access token là dữ liệu vô thời hạn.',
    role: 'security-engineer',
    seniority: 'senior',
    technologies: ['rest-api'],
    difficulty: 4,
  },
  {
    slug: 'graphql-n-plus-one',
    title: 'GraphQL và N+1',
    core: 'Resolver theo từng field dễ tạo N+1; dùng batching/caching theo request như DataLoader, quan sát query thực và vẫn enforce authorization tại resolver hoặc service boundary.',
    role: 'backend-engineer',
    seniority: 'mid-level',
    technologies: ['graphql', 'postgresql'],
    difficulty: 4,
  },
  {
    slug: 'grpc-deadline',
    title: 'gRPC deadline và cancellation',
    core: 'Client phải đặt deadline; server tôn trọng cancellation và truyền deadline xuống dependency. Retry chỉ cho operation idempotent với backoff và giới hạn để tránh retry storm.',
    role: 'backend-engineer',
    seniority: 'senior',
    technologies: ['grpc'],
    difficulty: 4,
  },
  {
    slug: 'websocket-resilience',
    title: 'WebSocket có khả năng phục hồi',
    core: 'Thiết kế reconnect có exponential backoff và jitter, heartbeat, resume/sync state sau reconnect, auth revalidation và giới hạn connection/message để tránh resource exhaustion.',
    role: 'backend-engineer',
    seniority: 'senior',
    technologies: ['websocket', 'nodejs'],
    difficulty: 4,
  },
  {
    slug: 'docker-image',
    title: 'Docker image hiệu quả và an toàn',
    core: 'Dùng multi-stage build, base image nhỏ và được cập nhật, .dockerignore, layer cache hợp lý, chạy non-root, pin dependency/image digest khi cần và không bake secret vào image.',
    role: 'devops-engineer',
    seniority: 'mid-level',
    technologies: ['docker'],
    difficulty: 3,
  },
  {
    slug: 'kubernetes-probes',
    title: 'Kubernetes probes',
    core: 'Readiness quyết định pod nhận traffic; liveness khởi động lại khi process kẹt; startup bảo vệ ứng dụng khởi động chậm. Probe sai có thể tạo restart loop hoặc gửi traffic quá sớm.',
    role: 'devops-engineer',
    seniority: 'mid-level',
    technologies: ['kubernetes'],
    difficulty: 3,
  },
  {
    slug: 'kubernetes-autoscaling',
    title: 'Autoscaling trên Kubernetes',
    core: 'HPA scale theo metric phù hợp và có latency; request/limit phải thực tế để scheduler và metric đáng tin. Cần xét bottleneck downstream, cooldown, queue depth và không dùng CPU làm proxy duy nhất cho mọi workload.',
    role: 'devops-engineer',
    seniority: 'senior',
    technologies: ['kubernetes'],
    difficulty: 4,
  },
  {
    slug: 'terraform-state',
    title: 'Terraform state',
    core: 'State ánh xạ cấu hình với resource thật, chứa dữ liệu nhạy cảm tiềm năng và phải dùng remote backend có locking, access control, encryption, backup/versioning; không sửa state thủ công nếu chưa hiểu hậu quả.',
    role: 'cloud-solutions-architect',
    seniority: 'senior',
    technologies: ['terraform'],
    difficulty: 4,
  },
  {
    slug: 'progressive-delivery',
    title: 'Progressive delivery',
    core: 'Canary/blue-green giảm blast radius bằng rollout theo từng phần, metric và ngưỡng rollback rõ ràng. Migration database phải backward-compatible trong giai đoạn hai version cùng chạy.',
    role: 'devops-engineer',
    seniority: 'senior',
    technologies: ['cicd-github-actions', 'kubernetes'],
    difficulty: 4,
  },
  {
    slug: 'linux-permissions',
    title: 'Linux permissions',
    core: 'Hiểu owner/group/other, read-write-execute khác nhau cho file và directory, umask, least privilege và không dùng chmod 777 để chữa lỗi quyền.',
    role: 'devops-engineer',
    seniority: 'junior',
    technologies: ['linux-systems'],
    difficulty: 2,
  },
  {
    slug: 'redis-eviction',
    title: 'Redis eviction',
    core: 'maxmemory và eviction policy quyết định key nào bị loại khi đầy; chọn theo workload, đặt TTL khi phù hợp, theo dõi eviction/hit rate/memory fragmentation và không coi Redis là durable database nếu chưa cấu hình persistence phù hợp.',
    role: 'backend-engineer',
    seniority: 'senior',
    technologies: ['redis'],
    difficulty: 4,
  },
  {
    slug: 'rabbitmq-dlq',
    title: 'RabbitMQ retry và dead-letter queue',
    core: 'Retry cần phân loại lỗi, backoff và giới hạn attempt; message poison đi DLQ để điều tra. Consumer phải idempotent, ack sau side effect bền vững và có metric cho backlog/DLQ.',
    role: 'backend-engineer',
    seniority: 'senior',
    technologies: ['rabbitmq'],
    difficulty: 4,
  },
  {
    slug: 'kafka-partitioning',
    title: 'Kafka partition và consumer group',
    core: 'Partition quyết định ordering theo partition và throughput; consumer cùng group chia partition. Key phải giữ ordering cho entity cần thiết, xử lý rebalance, offset commit và duplicate delivery.',
    role: 'data-engineer',
    seniority: 'senior',
    technologies: ['kafka'],
    difficulty: 4,
  },
  {
    slug: 'elasticsearch-mapping',
    title: 'Elasticsearch mapping',
    core: 'Mapping quyết định cách index/search; text dùng analyzer cho full-text, keyword cho exact/filter/aggregation. Mapping thay đổi thường cần reindex, nên thiết kế index version và alias rollout.',
    role: 'data-engineer',
    seniority: 'mid-level',
    technologies: ['elasticsearch'],
    difficulty: 3,
  },
  {
    slug: 'mongodb-modeling',
    title: 'MongoDB data modeling',
    core: 'Chọn embed khi dữ liệu được đọc/ghi cùng nhau và bounded; reference khi quan hệ lớn hoặc lifecycle độc lập. Thiết kế từ access pattern, index, document growth và transaction không mặc định thay cho mô hình đúng.',
    role: 'backend-engineer',
    seniority: 'mid-level',
    technologies: ['mongodb'],
    difficulty: 3,
  },
  {
    slug: 'dynamodb-partition',
    title: 'DynamoDB partition key',
    core: 'Partition key phân phối tải; hot key gây throttling. Thiết kế từ access pattern, dùng sort key và secondary index có chủ đích, hiểu capacity/consistent read và tránh scan cho luồng nóng.',
    role: 'backend-engineer',
    seniority: 'senior',
    technologies: ['dynamodb', 'aws'],
    difficulty: 4,
  },
  {
    slug: 'aws-iam',
    title: 'AWS IAM least privilege',
    core: 'Policy cần grant action/resource/condition tối thiểu, dùng role tạm thời thay access key dài hạn, tách human/workload identity, review policy và audit CloudTrail.',
    role: 'security-engineer',
    seniority: 'mid-level',
    technologies: ['aws'],
    difficulty: 3,
  },
  {
    slug: 'distributed-tracing',
    title: 'Distributed tracing',
    core: 'Trace liên kết một request qua service bằng trace/span context; propagation phải xuyên HTTP/message queue, sampling có chủ đích và attribute không được chứa secret/PII không cần thiết.',
    role: 'devops-engineer',
    seniority: 'senior',
    technologies: ['nodejs'],
    difficulty: 4,
  },
  {
    slug: 'sql-injection',
    title: 'Ngăn SQL injection',
    core: 'Dùng parameterized query/ORM đúng cách, không nối input vào SQL, validate theo allowlist nơi có dynamic identifier, giới hạn quyền DB và log an toàn. Escaping đơn thuần không phải phòng vệ chính.',
    role: 'security-engineer',
    seniority: 'mid-level',
    technologies: ['postgresql', 'nodejs'],
    difficulty: 3,
  },
  {
    slug: 'xss-csrf',
    title: 'XSS và CSRF',
    core: 'XSS là chèn script vào ngữ cảnh browser; ưu tiên output encoding theo context, CSP và tránh unsafe HTML. CSRF lợi dụng credential tự gửi; dùng SameSite, CSRF token hoặc origin check phù hợp. Hai vấn đề khác nhau.',
    role: 'security-engineer',
    seniority: 'mid-level',
    technologies: ['javascript', 'rest-api'],
    difficulty: 3,
  },
  {
    slug: 'secret-rotation',
    title: 'Secret rotation',
    core: 'Rotation cần inventory owner, version/dual-read khi cần, rollout theo thứ tự dependency, revoke credential cũ sau xác nhận, audit và runbook rollback; secret không xuất hiện trong source, image hay log.',
    role: 'security-engineer',
    seniority: 'senior',
    technologies: ['aws', 'kubernetes'],
    difficulty: 4,
  },
  {
    slug: 'threat-modeling',
    title: 'Threat modeling',
    core: 'Xác định asset, trust boundary, actor, data flow và threat trước khi chọn control. Ưu tiên theo impact/likelihood, gắn owner và kiểm thử control; threat model được cập nhật khi kiến trúc thay đổi.',
    role: 'security-engineer',
    seniority: 'senior',
    technologies: ['owasp-security'],
    difficulty: 4,
  },
  {
    slug: 'jwt-security',
    title: 'JWT security',
    core: 'Validate chữ ký, thuật toán allowlist, issuer, audience, expiry và not-before; không tin claim chưa verify, không đặt secret/PII vào payload, có chiến lược revocation/rotation và bảo vệ token trên client.',
    role: 'security-engineer',
    seniority: 'mid-level',
    technologies: ['nodejs', 'rest-api'],
    difficulty: 3,
  },
  {
    slug: 'playwright-locators',
    title: 'Locator bền vững trong Playwright',
    core: 'Ưu tiên locator theo role, label hoặc test id ổn định thay selector theo CSS structure; chờ assertion theo trạng thái người dùng thấy được, cô lập test data và không chữa flaky test bằng sleep cố định.',
    role: 'qa-qc-automation-engineer',
    seniority: 'mid-level',
    technologies: ['playwright'],
    difficulty: 3,
  },
  {
    slug: 'test-pyramid',
    title: 'Test pyramid và phạm vi test',
    core: 'Unit test nhanh cho logic; integration test cho boundary/dependency; E2E cho journey quan trọng. Chọn số lượng theo rủi ro và feedback speed, không đo chất lượng bằng coverage đơn thuần.',
    role: 'qa-qc-automation-engineer',
    seniority: 'mid-level',
    technologies: ['jest-vitest', 'playwright'],
    difficulty: 3,
  },
  {
    slug: 'flaky-test',
    title: 'Điều tra flaky test',
    core: 'Tái hiện, thu log/trace/video, xác định nguồn nondeterminism như race, clock, shared state, network hoặc selector; sửa nguyên nhân rồi đo recurrence. Retry chỉ là biện pháp giảm nhiễu tạm thời, không phải bằng chứng test ổn định.',
    role: 'qa-qc-automation-engineer',
    seniority: 'senior',
    technologies: ['playwright', 'jest-vitest'],
    difficulty: 4,
  },
  {
    slug: 'load-testing',
    title: 'Thiết kế load test',
    core: 'Mô hình traffic thật, warm-up, arrival rate/concurrency, dataset và dependency; đo latency percentile, error, saturation, throughput và bottleneck. Không suy ra capacity production từ một test không đại diện.',
    role: 'qa-qc-automation-engineer',
    seniority: 'senior',
    technologies: ['jmeter-k6'],
    difficulty: 4,
  },
  {
    slug: 'mobile-offline-sync',
    title: 'Offline sync trên mobile',
    core: 'Lưu local state bền vững, xếp hàng mutation có idempotency key, conflict resolution theo domain, sync khi có mạng và hiển thị trạng thái minh bạch. Không giả định last-write-wins luôn đúng.',
    role: 'mobile-engineer',
    seniority: 'senior',
    technologies: ['react-native'],
    difficulty: 4,
  },
  {
    slug: 'flutter-state',
    title: 'State management trong Flutter',
    core: 'Tách ephemeral UI state và app/domain state, chọn scope phù hợp, làm immutable update/deterministic side effect và kiểm thử logic ngoài widget khi có thể. Công cụ cụ thể ít quan trọng hơn ownership và data flow rõ ràng.',
    role: 'mobile-engineer',
    seniority: 'mid-level',
    technologies: ['flutter'],
    difficulty: 3,
  },
  {
    slug: 'go-context',
    title: 'context.Context trong Go',
    core: 'Context mang deadline, cancellation và request-scoped metadata; truyền xuống call chain, luôn gọi cancel khi tạo context có cancel và không dùng context để chứa dependency tùy ý.',
    role: 'backend-engineer',
    seniority: 'mid-level',
    technologies: ['golang'],
    difficulty: 3,
  },
  {
    slug: 'python-asyncio',
    title: 'asyncio và blocking I/O',
    core: 'asyncio tăng concurrency cho I/O cooperative; code CPU-bound hoặc blocking call vẫn chặn event loop. Dùng await đúng API, timeout/cancellation và chuyển CPU work sang process/worker khi cần.',
    role: 'backend-engineer',
    seniority: 'mid-level',
    technologies: ['python'],
    difficulty: 3,
  },
  {
    slug: 'csharp-async',
    title: 'async/await trong C#',
    core: 'async/await không tự tạo thread; nó giải phóng thread khi chờ I/O. Tránh .Result/.Wait gây block/deadlock, propagate CancellationToken và phân biệt CPU-bound với I/O-bound khi chọn Task.Run.',
    role: 'backend-engineer',
    seniority: 'mid-level',
    technologies: ['csharp'],
    difficulty: 3,
  },
  {
    slug: 'rust-ownership',
    title: 'Ownership và borrowing trong Rust',
    core: 'Ownership bảo đảm một owner cho giá trị; borrowing cho phép reference theo luật mutable hoặc nhiều immutable reference, lifetime ngăn dangling reference. Mục tiêu là memory safety không GC mà không bỏ qua thiết kế API rõ ràng.',
    role: 'backend-engineer',
    seniority: 'mid-level',
    technologies: ['rust'],
    difficulty: 3,
  },
  {
    slug: 'laravel-eloquent',
    title: 'Eloquent và N+1',
    core: 'Quan sát query do ORM tạo, eager load relation khi access pattern cần, chọn projection/pagination và không đổi tất cả relation sang eager. N+1 là vấn đề access pattern, không riêng Laravel.',
    role: 'backend-engineer',
    seniority: 'mid-level',
    technologies: ['php', 'laravel'],
    difficulty: 3,
  },
  {
    slug: 'fastapi-validation',
    title: 'Validation boundary trong FastAPI',
    core: 'Khai báo schema cho request/response, validate dữ liệu ngoài boundary, phân biệt lỗi client/server và không tin type hint như runtime security control duy nhất; authorization vẫn phải kiểm ở service/resource layer.',
    role: 'backend-engineer',
    seniority: 'junior',
    technologies: ['python', 'fastapi'],
    difficulty: 2,
  },
  {
    slug: 'django-transaction',
    title: 'Transaction trong Django ORM',
    core: 'Atomic block nhóm thay đổi cần cùng thành công, nhưng transaction dài gây lock/contention. Dùng constraint database cho invariant, xử lý IntegrityError/race và không thực hiện network side effect không kiểm soát bên trong transaction.',
    role: 'backend-engineer',
    seniority: 'mid-level',
    technologies: ['python', 'django', 'postgresql'],
    difficulty: 3,
  },
  {
    slug: 'rag-chunking',
    title: 'Chunking cho RAG',
    core: 'Chunk theo cấu trúc và ý nghĩa tài liệu, giữ metadata/source, chọn overlap có kiểm soát, đánh giá retrieval bằng dataset thật và không coi chunk size cố định là tối ưu mọi loại nội dung.',
    role: 'ai-ml-engineer',
    seniority: 'mid-level',
    technologies: ['langchain-rag'],
    difficulty: 3,
  },
  {
    slug: 'vector-retrieval',
    title: 'Vector retrieval',
    core: 'Embedding biểu diễn semantic similarity nhưng retrieval cần filter metadata, hybrid lexical/vector khi phù hợp, reranking và đánh giá recall/precision. Cần quản lý version embedding/index và quyền truy cập trước khi trả context cho model.',
    role: 'ai-ml-engineer',
    seniority: 'senior',
    technologies: ['langchain-rag'],
    difficulty: 4,
  },
  {
    slug: 'llm-evaluation',
    title: 'Đánh giá hệ thống LLM',
    core: 'Dùng eval set đại diện, rubric rõ ràng, metric theo rủi ro như groundedness/task success/safety, human review cho case quan trọng và theo dõi regression theo version prompt/model/retrieval.',
    role: 'ai-ml-engineer',
    seniority: 'senior',
    technologies: ['langchain-rag'],
    difficulty: 4,
  },
  {
    slug: 'ml-overfitting',
    title: 'Overfitting trong machine learning',
    core: 'Overfitting là model học cả noise của training nên generalization kém; dùng split đúng theo thời gian/group, baseline, regularization, data augmentation hoặc model đơn giản hơn và không tune trên test set.',
    role: 'ai-ml-engineer',
    seniority: 'mid-level',
    technologies: ['pytorch'],
    difficulty: 3,
  },
  {
    slug: 'data-leakage',
    title: 'Data leakage',
    core: 'Leakage xảy ra khi feature hoặc quy trình training chứa thông tin không có ở thời điểm prediction, gồm target leakage và split sai. Xác định prediction timestamp, build pipeline fit trên training only và kiểm tra feature lineage.',
    role: 'data-analyst-scientist',
    seniority: 'senior',
    technologies: ['pandas-numpy'],
    difficulty: 4,
  },
  {
    slug: 'spark-shuffle',
    title: 'Spark shuffle',
    core: 'Shuffle di chuyển dữ liệu giữa partition cho join/groupBy và thường đắt do network/disk/skew. Giảm bằng partitioning hợp lý, broadcast join khi phù hợp, filter sớm, xử lý skew và đo plan/metric thay vì chỉ tăng executor.',
    role: 'data-engineer',
    seniority: 'senior',
    technologies: ['spark'],
    difficulty: 4,
  },
  {
    slug: 'pipeline-idempotency',
    title: 'Idempotency cho data pipeline',
    core: 'Job retry phải cho kết quả tương đương một lần chạy: dùng partition/run ID, atomic commit hoặc merge/upsert, checkpoint/watermark và dedup theo business key. Không dùng timestamp hiện tại làm key duy nhất nếu retry cần tái lập.',
    role: 'data-engineer',
    seniority: 'senior',
    technologies: ['spark', 'postgresql'],
    difficulty: 4,
  },
  {
    slug: 'warehouse-modeling',
    title: 'Mô hình dữ liệu kho dữ liệu',
    core: 'Star schema tách fact đo lường và dimension mô tả, grain của fact phải rõ trước khi chọn measure; xử lý slowly changing dimension theo nhu cầu lịch sử và kiểm soát metric definition nhất quán.',
    role: 'data-engineer',
    seniority: 'mid-level',
    technologies: ['postgresql'],
    difficulty: 3,
  },
  {
    slug: 'experiment-metrics',
    title: 'Experiment và product metrics',
    core: 'Bắt đầu bằng hypothesis, primary metric, guardrail, unit randomization và thời gian chạy; tránh peeking/p-hacking, kiểm tra sample ratio mismatch và diễn giải effect size cùng uncertainty chứ không chỉ p-value.',
    role: 'data-analyst-scientist',
    seniority: 'senior',
    technologies: ['pandas-numpy'],
    difficulty: 4,
  },
  {
    slug: 'architecture-decision',
    title: 'Architecture Decision Record',
    core: 'ADR ghi context, decision, alternatives, trade-off và consequences để người sau hiểu lý do; quyết định có thể bị supersede, không phải tài liệu bất biến. Quy mô tài liệu tỷ lệ với rủi ro và tính khó đảo ngược.',
    role: 'engineering-manager-tech-lead',
    seniority: 'senior',
    technologies: [],
    difficulty: 4,
  },
  {
    slug: 'incident-communication',
    title: 'Giao tiếp trong incident',
    core: 'Incident update cần impact, phạm vi, hành động đang làm, owner, thời điểm cập nhật tiếp theo và điều chưa biết; tách kênh điều phối/technical, tránh suy đoán và giữ blameless review sau sự cố.',
    role: 'engineering-manager-tech-lead',
    seniority: 'senior',
    technologies: [],
    difficulty: 4,
  },
  {
    slug: 'azure-managed-identity',
    title: 'Managed identity trên Azure',
    core: 'Managed identity cho workload nhận token ngắn hạn từ Entra ID thay vì lưu credential ứng dụng; cần gán RBAC tối thiểu trên resource đích, xác minh audience và theo dõi lỗi token/permission.',
    role: 'cloud-solutions-architect',
    seniority: 'mid-level',
    technologies: ['azure'],
    difficulty: 3,
  },
];

const expandedPublishedSeeds = expansionTopics.flatMap(topic => [
  technical(
    `${topic.slug}-principles`,
    `${topic.title}: nguyên lý`,
    `Hãy giải thích nguyên lý cốt lõi của ${topic.title} và nêu điều kiện áp dụng.`,
    topic.core,
    topic.role,
    topic.seniority,
    topic.technologies,
    topic.difficulty,
  ),
  technical(
    `${topic.slug}-scenario`,
    `${topic.title}: xử lý tình huống`,
    `Bạn gặp một sự cố hoặc yêu cầu thay đổi liên quan đến ${topic.title}. Bạn sẽ điều tra, đưa ra phương án và xác minh kết quả như thế nào?`,
    `${topic.core} Với tình huống thực tế, cần bắt đầu bằng phạm vi/tác động, dùng tín hiệu quan sát được để xác minh giả thuyết, rollout thay đổi có kiểm soát và định nghĩa tiêu chí thành công hoặc rollback.`,
    topic.role,
    topic.seniority,
    topic.technologies,
    Math.min(5, topic.difficulty + 1),
    'scenario',
  ),
  technical(
    `${topic.slug}-tradeoffs`,
    `${topic.title}: trade-off`,
    `Những trade-off nào cần được nêu khi chọn giải pháp cho ${topic.title}?`,
    `${topic.core} Đánh giá trade-off qua correctness, độ trễ/throughput, độ phức tạp vận hành, chi phí, bảo mật và khả năng rollback; lựa chọn phải gắn với workload và SLO thay vì khẩu hiệu.`,
    topic.role,
    topic.seniority,
    topic.technologies,
    topic.difficulty,
    'conceptual',
  ),
  technical(
    `${topic.slug}-review`,
    `${topic.title}: review triển khai`,
    `Khi review một pull request hoặc thiết kế liên quan đến ${topic.title}, bạn sẽ kiểm tra những gì trước?`,
    `${topic.core} Review cần kiểm contract, edge case, test/observability, quyền truy cập và ảnh hưởng tới dependency. Yêu cầu tác giả nêu giả định và bằng chứng thay vì chỉ áp quy tắc máy móc.`,
    topic.role,
    topic.seniority,
    topic.technologies,
    topic.difficulty,
    'scenario',
  ),
]);

export const questionBankDrafts: QuestionSeedDraft[] = [
  ...expandedPublishedSeeds,
  // JavaScript and TypeScript
  technical(
    'js-event-loop-microtask-order',
    'Thứ tự microtask và task trong JavaScript',
    'Đoạn mã có Promise.resolve().then(...), queueMicrotask(...) và setTimeout(..., 0). Hãy giải thích thứ tự chạy ở mức khái niệm và lý do.',
    'Mã đồng bộ chạy hết stack trước. Sau khi task hiện tại kết thúc, runtime xử lý hàng microtask đến khi rỗng; callback Promise và queueMicrotask thuộc microtask. Callback setTimeout là task nên chỉ được xét ở vòng lặp sau. Thứ tự giữa các microtask tuân theo thứ tự được xếp hàng, nhưng không nên dựa vào chi tiết riêng của Node.js hoặc trình duyệt nếu câu hỏi không nêu runtime.',
    'frontend-engineer',
    'mid-level',
    ['javascript'],
    3,
  ),
  technical(
    'js-closure-memory-lifecycle',
    'Closure giữ dữ liệu như thế nào?',
    'Closure là gì? Khi nào closure có thể làm đối tượng sống lâu hơn dự kiến và bạn xử lý ra sao?',
    'Closure là hàm cùng môi trường lexical của nó; biến được tham chiếu vẫn có thể truy cập sau khi hàm ngoài kết thúc. Nó hữu ích cho encapsulation và callback, nhưng listener, timer, cache hoặc callback dài hạn có thể vô tình giữ tham chiếu đến object lớn. Cách xử lý là bỏ listener/timer, giới hạn cache, chỉ capture dữ liệu cần thiết và dùng profiling để xác nhận retention.',
    'frontend-engineer',
    'mid-level',
    ['javascript'],
    3,
  ),
  technical(
    'typescript-unknown-vs-any',
    'Phân biệt unknown và any trong TypeScript',
    'Khi nhận dữ liệu từ API không đáng tin cậy, vì sao nên ưu tiên unknown hơn any?',
    'any tắt phần lớn kiểm tra kiểu và cho phép thao tác không an toàn. unknown buộc code thu hẹp kiểu bằng guard, typeof, instanceof hoặc schema validation trước khi dùng. Với dữ liệu bên ngoài, dùng unknown ở ranh giới rồi parse/validate thành kiểu domain giúp lỗi nằm gần điểm vào và giữ phần còn lại của ứng dụng type-safe.',
    'frontend-engineer',
    'junior',
    ['typescript'],
    2,
  ),
  technical(
    'typescript-discriminated-union',
    'Dùng discriminated union cho trạng thái bất đồng bộ',
    'Hãy thiết kế kiểu TypeScript mô tả loading, success và error mà không cần các boolean mâu thuẫn như isLoading và hasError.',
    'Dùng union có trường discriminator, ví dụ status: loading | success | error; success mang data, error mang error. Khi switch theo status, TypeScript có thể narrow kiểu và exhaustive check bằng never. Mô hình này loại bỏ trạng thái không hợp lệ như vừa loading vừa có data lỗi, đồng thời làm UI xử lý từng trường hợp rõ ràng.',
    'frontend-engineer',
    'mid-level',
    ['typescript'],
    3,
  ),
  technical(
    'js-prototype-inheritance',
    'Prototype chain hoạt động ra sao?',
    'Khi đọc obj.method(), JavaScript tìm method theo thứ tự nào? Điều này khác gì với việc copy method vào từng instance?',
    'Engine tìm property trên chính obj trước, rồi lần lượt đi theo prototype chain cho đến null. Method đặt trên prototype được chia sẻ giữa các instance, trong khi method tạo trong constructor cho mỗi instance một function riêng. Cần phân biệt lookup runtime với cú pháp class: class vẫn dựa trên prototype, còn private field có semantics riêng.',
    'frontend-engineer',
    'junior',
    ['javascript'],
    2,
  ),
  technical(
    'js-equality-object-reference',
    'So sánh object trong JavaScript',
    'Vì sao {} === {} là false? Bạn sẽ so sánh dữ liệu object khi nào theo tham chiếu, khi nào theo giá trị?',
    'Object được so sánh bằng identity tham chiếu, nên hai literal khác nhau là hai object khác nhau. So sánh tham chiếu phù hợp để phát hiện cùng instance hoặc tối ưu render immutable. So sánh theo giá trị cần quy tắc domain rõ ràng: so từng field cần thiết, dùng deep equality có kiểm soát hoặc canonical representation; không nên dùng JSON.stringify một cách mù quáng vì thứ tự key, undefined, Date, Map và cyclic reference.',
    'frontend-engineer',
    'junior',
    ['javascript'],
    2,
  ),
  technical(
    'js-async-error-handling',
    'Xử lý lỗi bất đồng bộ đáng tin cậy',
    'Bạn thiết kế xử lý lỗi cho chuỗi async/await gọi API như thế nào để UI không nuốt lỗi và không cập nhật state sau unmount?',
    'Bọc operation có thể fail trong try/catch, phân loại lỗi có thể xử lý (validation, unauthorized, network, server), hiển thị thông điệp an toàn và log metadata cần thiết. Dùng AbortController hoặc cờ lifecycle phù hợp để hủy/ignore kết quả cũ khi component không còn quan tâm. finally chỉ dọn trạng thái của request còn hiệu lực; tránh catch rỗng hoặc biến mọi lỗi thành cùng một thông báo.',
    'frontend-engineer',
    'mid-level',
    ['javascript'],
    3,
    'scenario',
  ),
  technical(
    'typescript-generic-api-client',
    'Thiết kế generic cho API client',
    'Generic giúp gì cho API client TypeScript, và generic không thể thay thế điều gì ở ranh giới mạng?',
    'Generic mô tả quan hệ kiểu giữa request và response, giúp caller nhận đúng type tại compile time. Tuy nhiên response HTTP là dữ liệu runtime, có thể sai hoặc bị thay đổi; generic không validate payload. API client nên parse unknown bằng schema/runtime validator, map sang domain model và xử lý version/compatibility ở boundary.',
    'fullstack-engineer',
    'mid-level',
    ['typescript', 'rest-api'],
    3,
  ),
  technical(
    'js-debounce-throttle-selection',
    'Chọn debounce hay throttle cho tương tác người dùng',
    'So sánh debounce và throttle trong ô tìm kiếm, resize và drag. Nêu trade-off UX.',
    'Debounce chờ một khoảng im lặng rồi mới chạy, phù hợp search khi muốn giảm request sau khi người dùng dừng gõ. Throttle giới hạn tần suất nhưng vẫn chạy định kỳ, phù hợp scroll, resize hoặc drag khi cần phản hồi liên tục. Cần cân nhắc leading/trailing call, hủy timer khi unmount và không để độ trễ làm UI có cảm giác bị kẹt.',
    'frontend-engineer',
    'junior',
    ['javascript'],
    2,
  ),
  technical(
    'typescript-compiler-vs-runtime',
    'TypeScript tồn tại ở runtime không?',
    'TypeScript bảo vệ được những gì, và tại sao code vẫn cần validation input ở runtime?',
    'TypeScript bị xóa khi biên dịch sang JavaScript; nó kiểm tra tĩnh trong quá trình build/editor chứ không xác thực request, JSON, biến môi trường hay dữ liệu database lúc chạy. Vì vậy cần validation runtime ở các boundary, đồng thời dùng TypeScript để làm các invariants nội bộ rõ ràng và giảm lỗi trước khi chạy.',
    'backend-engineer',
    'junior',
    ['typescript'],
    2,
  ),

  // React
  technical(
    'react-render-commit-effect',
    'Render, commit và Effect trong React',
    'Hãy mô tả render khác commit thế nào, và useEffect phù hợp cho loại công việc nào?',
    'Render tính UI mong muốn từ props/state và phải thuần; commit áp dụng thay đổi vào DOM. useEffect dùng để đồng bộ component với hệ thống bên ngoài như network subscription, timer hoặc widget không do React quản lý, đồng thời trả cleanup khi cần. Nếu chỉ biến đổi dữ liệu để render, nên tính trong render hoặc memo hóa khi có bằng chứng về chi phí, không dùng Effect để tạo state dư thừa.',
    'frontend-engineer',
    'mid-level',
    ['react'],
    3,
  ),
  technical(
    'react-effect-dependencies',
    'Dependency array của useEffect',
    'Vì sao bỏ dependency để Effect “chạy ít hơn” thường tạo stale closure? Cách sửa đúng là gì?',
    'Effect đóng trên props/state của render đã tạo nó. Mọi reactive value được đọc trong Effect phải được khai báo dependency, trừ khi tái cấu trúc logic để nó không còn reactive. Cách sửa có thể là đưa function/object ra ngoài component, dùng functional state update, tách Effect, memo hóa khi thực sự cần, hoặc chuyển logic về event handler; không tắt lint rule để che lỗi.',
    'frontend-engineer',
    'mid-level',
    ['react'],
    3,
  ),
  technical(
    'react-state-immutability',
    'Vì sao không mutate state React?',
    'Điều gì có thể xảy ra khi sửa trực tiếp object hoặc array trong state rồi gọi setter với cùng tham chiếu?',
    'React và memoization thường dựa vào thay đổi tham chiếu để nhận biết dữ liệu mới. Mutate rồi trả lại cùng object có thể không trigger render đúng, làm lịch sử state khó suy luận và gây lỗi khi concurrent rendering. Hãy tạo object/array mới cho phần thay đổi, hoặc dùng thư viện immutable có kỷ luật rõ ràng.',
    'frontend-engineer',
    'junior',
    ['react', 'javascript'],
    2,
  ),
  technical(
    'react-keys-list-reconciliation',
    'Key trong danh sách React',
    'Vì sao không nên dùng index làm key cho danh sách có thể chèn, xóa hoặc sắp xếp lại?',
    'Key xác định identity của item giữa các lần render. Index thay đổi khi reorder/chèn/xóa khiến state cục bộ, focus hoặc input value bị gán nhầm sang item khác. Dùng ID ổn định từ domain; chỉ dùng index khi danh sách thực sự tĩnh, không có state theo item và không thể reorder.',
    'frontend-engineer',
    'junior',
    ['react'],
    2,
  ),
  technical(
    'react-controlled-uncontrolled-inputs',
    'Controlled và uncontrolled input',
    'Khi nào chọn controlled input, khi nào ref/uncontrolled input có thể phù hợp?',
    'Controlled input lấy value từ React state và cập nhật qua handler, phù hợp validation tức thời, UI phụ thuộc nhiều field và một nguồn dữ liệu rõ ràng. Uncontrolled input để DOM giữ value, đọc qua ref hoặc FormData, phù hợp form đơn giản/tích hợp thư viện và giảm render. Không trộn hai mô hình cho cùng một input trong vòng đời component.',
    'frontend-engineer',
    'junior',
    ['react'],
    2,
  ),
  technical(
    'react-context-performance',
    'Context và hiệu năng render',
    'Context có thể gây re-render rộng như thế nào, và bạn giảm tác động ra sao?',
    'Khi value của Provider đổi identity, consumer phụ thuộc context có thể render lại. Tách context theo mối quan tâm, giữ value ổn định khi hợp lý, đặt Provider gần nơi cần dùng và dùng state management/selector phù hợp cho dữ liệu thay đổi nhanh. Không memo hóa mọi thứ theo phản xạ; trước hết profile để xác định render nào có chi phí.',
    'frontend-engineer',
    'senior',
    ['react'],
    4,
  ),
  technical(
    'react-data-fetch-race',
    'Tránh race condition khi fetch dữ liệu',
    'Người dùng đổi nhanh từ profile A sang B, request A về sau request B. Bạn ngăn UI hiển thị A như thế nào?',
    'Gắn lifecycle của request với input hiện tại: hủy request cũ bằng AbortController nếu thư viện hỗ trợ, hoặc chỉ chấp nhận response có request key/version còn mới nhất. State cần thể hiện loading/error theo đúng key. Một data-fetching library có cache và request deduplication giúp chuẩn hóa, nhưng vẫn cần hiểu cancellation và stale data policy.',
    'frontend-engineer',
    'mid-level',
    ['react', 'javascript'],
    3,
    'debugging',
  ),
  technical(
    'react-error-boundary-scope',
    'Error Boundary bắt được gì?',
    'Error Boundary có bắt lỗi từ event handler, async callback hoặc SSR không? Bạn thiết kế fallback thế nào?',
    'Error Boundary bắt lỗi render/lifecycle của subtree client theo cơ chế React, không thay thế try/catch cho event handler hoặc Promise; lỗi async cần xử lý tại nơi khởi phát. Fallback cần có thông điệp an toàn, correlation ID nếu có, hành động thử lại/quay lại và telemetry không chứa dữ liệu nhạy cảm. Hãy đặt boundary theo vùng nghiệp vụ để một lỗi không làm hỏng toàn bộ ứng dụng.',
    'frontend-engineer',
    'senior',
    ['react'],
    4,
  ),
  technical(
    'react-usememo-usecallback',
    'Khi nào dùng useMemo và useCallback?',
    'Hai Hook này giải quyết vấn đề gì và rủi ro khi lạm dụng là gì?',
    'useMemo cache kết quả tính toán, useCallback cache identity của function giữa các render khi dependency không đổi. Chúng hữu ích khi có tính toán đắt tiền hoặc identity ổn định giúp child memoized/hook khác tránh công việc không cần thiết. Chúng không phải semantic guarantee và có overhead/complexity; profile trước, giữ dependency đúng và đừng dùng chúng để sửa logic Effect sai.',
    'frontend-engineer',
    'mid-level',
    ['react'],
    3,
  ),
  technical(
    'react-accessible-modal',
    'Thiết kế modal có khả năng truy cập',
    'Nêu các yêu cầu thiết yếu của modal dialog có thể dùng bằng bàn phím và screen reader.',
    'Modal cần role/label phù hợp, focus chuyển vào dialog khi mở và được restore khi đóng, Tab được giữ trong dialog, Escape có hành vi dự đoán được nếu được phép đóng, và background không còn tương tác/focus. Nội dung phải đọc được với screen reader; không chỉ dựa vào overlay click. Kiểm thử bằng keyboard và công cụ trợ năng, đặc biệt khi có nested modal hoặc async loading.',
    'frontend-engineer',
    'mid-level',
    ['react', 'html5-css3'],
    3,
  ),

  // Node.js and API engineering
  technical(
    'node-event-loop-blocking',
    'Nhận diện code chặn event loop Node.js',
    'Một endpoint Node.js chậm mọi request khác khi xử lý file lớn. Bạn điều tra và khắc phục theo hướng nào?',
    'Xác minh bằng metrics event-loop delay, CPU profile và trace theo request. Tránh vòng lặp CPU nặng hoặc I/O sync trên main thread; dùng streaming cho dữ liệu lớn, worker thread/process/job queue cho CPU-bound work, đặt giới hạn kích thước và timeout. Không giả định mọi async API tự động giải quyết CPU-bound workload.',
    'backend-engineer',
    'senior',
    ['nodejs'],
    4,
    'debugging',
  ),
  technical(
    'node-stream-backpressure',
    'Backpressure trong Node.js stream',
    'Backpressure là gì và vì sao phải tôn trọng giá trị trả về của writable.write()?',
    'Backpressure xảy ra khi producer tạo dữ liệu nhanh hơn consumer ghi/xử lý. Khi writable.write() trả false, producer cần chờ drain hoặc dùng pipeline để runtime phối hợp; nếu tiếp tục ghi, bộ nhớ có thể tăng không kiểm soát. pipeline còn giúp lan truyền lỗi và cleanup giữa stream nguồn/đích.',
    'backend-engineer',
    'mid-level',
    ['nodejs'],
    3,
  ),
  technical(
    'rest-idempotency-key',
    'Thiết kế idempotency cho POST tạo thanh toán',
    'Bạn làm gì để retry từ client không tạo hai giao dịch khi mạng bị ngắt sau khi server đã xử lý?',
    'Yêu cầu idempotency key duy nhất theo người dùng và operation, lưu request fingerprint cùng kết quả hoặc trạng thái xử lý trong transaction, và trả lại kết quả cũ cho retry cùng key. Key dùng với payload khác phải bị từ chối. Cần nêu TTL, concurrent request, trạng thái pending/unknown và bảo đảm side effect downstream cũng idempotent hoặc được điều phối bằng outbox.',
    'backend-engineer',
    'senior',
    ['nodejs', 'rest-api', 'postgresql'],
    5,
    'scenario',
  ),
  technical(
    'api-pagination-cursor',
    'Cursor pagination và offset pagination',
    'So sánh cursor với offset khi danh sách thay đổi liên tục.',
    'Offset đơn giản và tiện cho nhảy trang nhưng có thể chậm ở offset lớn và bị duplicate/missing item khi dữ liệu thay đổi. Cursor dựa trên sort key ổn định, thường kết hợp tie-breaker duy nhất như id, cho traversal nhất quán và hiệu quả hơn. API phải quy định sort order, encode cursor an toàn, xử lý item bị xóa và không coi cursor là dữ liệu đáng tin từ client.',
    'backend-engineer',
    'mid-level',
    ['nodejs', 'rest-api'],
    3,
  ),
  technical(
    'api-authentication-authorization',
    'Authentication khác authorization',
    'Tại sao kiểm tra JWT hợp lệ chưa đủ để bảo vệ endpoint cập nhật tài nguyên?',
    'Authentication xác minh danh tính; authorization kiểm tra principal đó có được thực hiện action trên resource cụ thể hay không. Endpoint phải kiểm policy server-side theo user/tenant/role/ownership, không tin role hay ownerId do client gửi và không dựa vào UI ẩn nút. Cần kiểm thử BOLA/IDOR bằng tài khoản khác tenant hoặc khác owner.',
    'backend-engineer',
    'mid-level',
    ['nodejs', 'rest-api'],
    3,
  ),
  technical(
    'nestjs-provider-scope',
    'Provider scope trong NestJS',
    'Singleton, request scope và transient scope khác nhau thế nào? Khi nào request scope gây hại?',
    'Provider mặc định singleton, phù hợp service stateless và connection pool dùng chung. Request scope tạo instance theo request để mang context nhưng tăng chi phí, có thể lan scope lên dependency chain và làm cache/DI phức tạp. Transient tạo instance theo injection. Ưu tiên truyền context rõ ràng hoặc AsyncLocalStorage có kiểm soát khi cần correlation; chỉ dùng request scope khi lợi ích lớn hơn chi phí.',
    'backend-engineer',
    'mid-level',
    ['nestjs'],
    3,
  ),
  technical(
    'nestjs-validation-boundary',
    'Validation DTO ở ranh giới API',
    'ValidationPipe giải quyết gì, và vì sao validation DTO không thay thế authorization hay business invariants?',
    'DTO validation kiểm tra shape/kiểu/ràng buộc cú pháp của input trước khi vào handler. Nó không biết caller có quyền hay không, không đảm bảo uniqueness dưới cạnh tranh, và không kiểm tra invariant phụ thuộc dữ liệu hiện có. Hãy kết hợp validation, policy authorization, transaction/constraint database và error mapping rõ ràng.',
    'backend-engineer',
    'junior',
    ['nestjs', 'typescript'],
    2,
  ),
  technical(
    'node-graceful-shutdown',
    'Graceful shutdown cho API Node.js',
    'Pod nhận SIGTERM trong lúc có request và job đang chạy. Dịch vụ cần làm gì?',
    'Ngừng nhận kết nối mới hoặc mark unready, cho request đang chạy hoàn tất trong deadline, dừng consumer nhận job mới, flush/commit trạng thái cần thiết rồi đóng server, DB/Redis connection. Có timeout cưỡng bức để không treo deploy, nhưng phải quan sát số request/job bị hủy. Shutdown handler cần idempotent vì signal có thể đến nhiều lần.',
    'backend-engineer',
    'senior',
    ['nodejs', 'kubernetes'],
    4,
    'scenario',
  ),
  technical(
    'api-rate-limit-design',
    'Thiết kế rate limit công bằng',
    'Bạn chọn key, thuật toán và response như thế nào cho rate limit API công khai?',
    'Chọn key theo identity đáng tin (API key/user/tenant), có thể kết hợp IP như tín hiệu phụ; không chỉ tin header client. Token bucket/leaky bucket cho phép burst có kiểm soát, fixed window đơn giản nhưng có boundary burst, sliding window chính xác hơn nhưng tốn tài nguyên hơn. Trả 429 cùng thông tin retry rõ ràng, có quota theo endpoint nhạy cảm và lưu state phân tán nhất quán.',
    'backend-engineer',
    'senior',
    ['nodejs', 'redis', 'rest-api'],
    4,
  ),
  technical(
    'node-logging-sensitive-data',
    'Logging an toàn cho backend',
    'Những dữ liệu nào không nên log toàn bộ, và bạn tổ chức log request như thế nào?',
    'Không log password, token, cookie, secret, body chứa PII hoặc đáp án private đầy đủ. Dùng structured log với correlation ID, route, status, duration, error code và metadata đã redaction; phân quyền truy cập log và đặt retention phù hợp. Log phải hỗ trợ điều tra nhưng không trở thành kênh rò rỉ dữ liệu.',
    'backend-engineer',
    'mid-level',
    ['nodejs'],
    3,
  ),

  // Java and Spring Boot
  technical(
    'java-equals-hashcode-contract',
    'Contract equals và hashCode',
    'Điều gì có thể xảy ra nếu override equals mà không override hashCode cho object làm key của HashMap?',
    'Hai object được equals là true phải có cùng hashCode. Vi phạm contract khiến HashMap/HashSet có thể không tìm thấy key “bằng nhau”, tạo duplicate hoặc hành vi khó đoán. Field dùng cho equals/hashCode nên ổn định trong thời gian object nằm trong hash-based collection; tránh mutable key.',
    'backend-engineer',
    'junior',
    ['java'],
    2,
  ),
  technical(
    'java-checked-unchecked-exceptions',
    'Checked và unchecked exception',
    'Bạn quyết định exception nào cần được caller xử lý/tuyên bố như thế nào?',
    'Checked exception phù hợp khi caller có thể phục hồi hợp lý và contract muốn buộc xử lý; unchecked thường biểu thị vi phạm precondition, programming error hoặc lỗi không thể phục hồi ngay tại caller. Quan trọng hơn là semantic rõ ràng, preserve cause, không catch rồi nuốt lỗi và map lỗi ra API một cách an toàn. Không dùng checked exception chỉ vì lỗi đến từ I/O nếu abstraction đã có chiến lược retry/fallback khác.',
    'backend-engineer',
    'mid-level',
    ['java'],
    3,
  ),
  technical(
    'java-concurrency-volatile-atomic',
    'volatile, Atomic và synchronized',
    'volatile có đảm bảo thao tác count++ an toàn giữa nhiều thread không?',
    'Không. volatile bảo đảm visibility và một số ordering cho đọc/ghi biến, nhưng count++ là read-modify-write gồm nhiều bước nên không atomic. Dùng AtomicInteger cho counter đơn giản, synchronized/lock khi cần bảo vệ invariant nhiều biến, hoặc cấu trúc concurrent phù hợp. Cần phân biệt visibility, atomicity và mutual exclusion.',
    'backend-engineer',
    'mid-level',
    ['java'],
    3,
  ),
  technical(
    'spring-transaction-proxy',
    'Giới hạn của @Transactional',
    'Vì sao gọi một method @Transactional từ method khác trong cùng instance có thể không tạo transaction như mong đợi?',
    'Trong cấu hình proxy thông thường, Spring áp dụng transaction khi call đi qua proxy. Self-invocation đi thẳng trên this nên có thể bỏ qua interceptor. Cách thiết kế tốt là tách transaction boundary sang bean khác, dùng programmatic transaction khi thật cần hoặc hiểu rõ proxy/aspect configuration. Cũng phải nói về propagation, rollback rule và việc transaction không tự giải quyết side effect ngoài DB.',
    'backend-engineer',
    'senior',
    ['java', 'spring-boot'],
    4,
  ),
  technical(
    'spring-transaction-isolation',
    'Chọn isolation level cho nghiệp vụ đặt hàng',
    'Khi tồn kho có nguy cơ oversell, bạn phân tích isolation, locking và constraint như thế nào?',
    'Bắt đầu từ invariant: không bán quá tồn và update phải atomic. Dùng conditional update hoặc row lock phù hợp, constraint/check khi mô hình hỗ trợ, transaction ngắn và retry có kiểm soát cho serialization/deadlock. Isolation level là một phần của giải pháp: higher isolation tăng consistency nhưng có chi phí/abort; không nên chỉ đặt SERIALIZABLE mà không xử lý retry và thiết kế truy vấn.',
    'backend-engineer',
    'senior',
    ['java', 'spring-boot', 'postgresql'],
    5,
    'scenario',
  ),
  technical(
    'spring-n-plus-one',
    'Phát hiện và xử lý N+1 query',
    'N+1 query thường xuất hiện ở đâu trong JPA/Hibernate và bạn xác minh bằng gì?',
    'N+1 thường xuất hiện khi load danh sách entity rồi lazy-load relation cho từng item. Xác minh bằng SQL log/tracing/metrics thay vì đoán. Tùy use case, dùng fetch join, EntityGraph, batch fetching hoặc projection DTO; không đổi mọi relation sang EAGER vì có thể tạo graph lớn, duplicate row và query ngoài ý muốn.',
    'backend-engineer',
    'mid-level',
    ['java', 'spring-boot', 'postgresql'],
    4,
    'debugging',
  ),
  technical(
    'spring-rest-error-contract',
    'Chuẩn hóa lỗi REST trong Spring Boot',
    'Bạn thiết kế error response như thế nào để client xử lý được mà không lộ chi tiết nội bộ?',
    'Dùng format nhất quán gồm stable machine-readable code, HTTP status, thông điệp an toàn, field errors khi validation và correlation ID. Map exception tập trung qua @ControllerAdvice hoặc cơ chế tương đương; log stack trace ở server theo chính sách redaction. Không trả SQL, stack trace, token hay thông tin user khác cho client.',
    'backend-engineer',
    'mid-level',
    ['java', 'spring-boot', 'rest-api'],
    3,
  ),
  technical(
    'java-optional-api-boundary',
    'Dùng Optional đúng ngữ cảnh',
    'Vì sao Optional thường phù hợp cho return type hơn field của entity hoặc tham số method public?',
    'Optional diễn đạt khả năng không có giá trị ở return type và buộc caller cân nhắc case absent. Dùng nó làm field/parameter có thể làm serialization, JPA và API khó tương thích, đồng thời tạo nhiều wrapper không cần thiết. Không gọi get() vô điều kiện; dùng map, orElseGet, orElseThrow với thông điệp/domain error phù hợp.',
    'backend-engineer',
    'junior',
    ['java'],
    2,
  ),
  technical(
    'spring-configuration-secrets',
    'Quản lý cấu hình và secret Spring Boot',
    'Bạn tách config theo môi trường và tránh rò rỉ secret trong log/repository ra sao?',
    'Cấu hình không nhạy cảm có thể versioned theo environment contract; secret lấy từ secret manager hoặc injected environment, không commit vào repo hay image. Validate config lúc startup, tránh log toàn bộ Environment/properties, rotation có quy trình và quyền đọc theo least privilege. Mỗi môi trường cần key/credential riêng và audit access.',
    'backend-engineer',
    'mid-level',
    ['java', 'spring-boot'],
    3,
  ),
  technical(
    'java-immutability-thread-safety',
    'Immutability hỗ trợ thread safety như thế nào?',
    'Một class immutable cần những điều kiện gì khi chứa collection hoặc object mutable?',
    'State được thiết lập khi tạo, không có setter/mutator, field thường final và không làm lộ mutable internal state. Với collection/object mutable phải defensive copy khi nhận và khi trả, hoặc dùng type immutable thật sự. Immutability giảm shared-state bugs nhưng không biến dependency mutable hay operation nhiều bước thành thread-safe một cách tự động.',
    'backend-engineer',
    'mid-level',
    ['java'],
    3,
  ),

  // PostgreSQL and database
  technical(
    'sql-index-btree-selection',
    'Khi nào B-tree index hữu ích?',
    'B-tree index thường phù hợp với kiểu truy vấn nào và vì sao không phải cột nào cũng nên index?',
    'B-tree là default tốt cho equality và range ordering phổ biến. Index có chi phí write, storage và vacuum/analyze; index ít selectivity hoặc không khớp access pattern có thể không giúp. Chọn index từ workload và EXPLAIN (ANALYZE, BUFFERS) trong môi trường an toàn, xem composite index theo predicate/order, không theo trực giác.',
    'backend-engineer',
    'mid-level',
    ['postgresql'],
    3,
  ),
  technical(
    'sql-composite-index-order',
    'Thứ tự cột trong composite index',
    'Với truy vấn lọc tenant_id, status và sắp xếp created_at, bạn cân nhắc thứ tự index như thế nào?',
    'Bắt đầu từ truy vấn thật và selectivity. Equality predicate thường đứng trước, sau đó range/order tùy access pattern; ví dụ index có thể bắt đầu tenant_id, status rồi created_at nếu các điều kiện đầu là equality và sort phù hợp. Không có thứ tự đúng chung: cần xem biến thể query, cardinality, index-only scan, write overhead và EXPLAIN actual.',
    'backend-engineer',
    'senior',
    ['postgresql'],
    4,
  ),
  technical(
    'postgres-mvcc-basics',
    'MVCC trong PostgreSQL',
    'MVCC giúp reader và writer cùng hoạt động như thế nào, và hậu quả vận hành là gì?',
    'PostgreSQL dùng version row và snapshot để transaction đọc dữ liệu nhất quán mà thường không chặn writer như lock-based model thuần túy. Row cũ cần được vacuum dọn khi không còn transaction nào cần thấy; transaction dài có thể giữ snapshot lâu, gây bloat và cản trở cleanup. Vẫn có lock, conflict và isolation anomalies cần được hiểu riêng.',
    'backend-engineer',
    'senior',
    ['postgresql'],
    4,
  ),
  technical(
    'postgres-read-committed-repeatable-read',
    'Read Committed và Repeatable Read',
    'Trong PostgreSQL, hai isolation level này khác nhau thế nào đối với snapshot đọc?',
    'Ở Read Committed, mỗi statement thường thấy snapshot mới của dữ liệu đã commit trước statement đó. Repeatable Read giữ snapshot nhất quán cho transaction, nên các statement sau không tự thấy commit mới từ transaction khác. Cần chọn theo invariant và xử lý serialization failure khi dùng level cao hơn; không suy luận behavior từ DBMS khác vì chi tiết triển khai khác nhau.',
    'backend-engineer',
    'senior',
    ['postgresql'],
    4,
  ),
  technical(
    'sql-null-three-valued-logic',
    'NULL và logic ba giá trị SQL',
    'Vì sao WHERE column <> 5 không trả các row có column là NULL?',
    'So sánh với NULL cho UNKNOWN, không phải true; WHERE chỉ giữ true nên row NULL bị loại. Dùng IS NULL/IS NOT NULL để kiểm tra null và cân nhắc IS DISTINCT FROM khi muốn so sánh null-safe. Không dùng = NULL hay <> NULL để kiểm tra null.',
    'backend-engineer',
    'junior',
    ['postgresql'],
    2,
  ),
  technical(
    'sql-join-cardinality',
    'Giải thích cardinality của JOIN',
    'Một JOIN làm số row tăng bất ngờ. Bạn kiểm tra quan hệ và query ra sao?',
    'Xác định khóa và cardinality thật của từng bảng, đặc biệt one-to-many hoặc many-to-many. Kiểm tra điều kiện join có thiếu key không, duplicate có phải đúng domain không và aggregation cần đặt ở đâu. DISTINCT chỉ nên là giải pháp khi semantic thực sự cần deduplicate; dùng nó để che join sai có thể làm mất dữ liệu và chậm query.',
    'backend-engineer',
    'mid-level',
    ['postgresql'],
    3,
  ),
  technical(
    'postgres-explain-analyze-safely',
    'Đọc EXPLAIN ANALYZE',
    'Khi nào dùng EXPLAIN và khi nào cần thận trọng với EXPLAIN ANALYZE?',
    'EXPLAIN cho execution plan ước tính mà không chạy query. EXPLAIN ANALYZE chạy query thật để có actual rows/time, nên statement ghi có thể tạo side effect nếu không bọc transaction rollback trong môi trường an toàn. So sánh estimated và actual rows để tìm statistics/cardinality issue, xem scan type, loops, buffers và không tối ưu chỉ từ một metric.',
    'backend-engineer',
    'mid-level',
    ['postgresql'],
    3,
  ),
  technical(
    'database-unique-constraint-race',
    'Ngăn duplicate dưới cạnh tranh',
    'Tại sao “SELECT xem có tồn tại rồi INSERT” không đủ để bảo đảm email duy nhất?',
    'Hai transaction có thể cùng đọc “chưa tồn tại” rồi cùng insert. Invariant uniqueness phải được database enforce bằng unique constraint/index; application xử lý lỗi conflict hoặc dùng upsert phù hợp. Transaction/lock có thể bổ sung cho invariant phức tạp, nhưng không thay thế constraint đơn giản và đáng tin cậy.',
    'backend-engineer',
    'mid-level',
    ['postgresql'],
    3,
    'scenario',
  ),
  technical(
    'postgres-connection-pooling',
    'Connection pool không phải vô hạn',
    'Vì sao tăng pool size thường không phải cách đầu tiên để xử lý chậm database?',
    'Mỗi connection tiêu thụ tài nguyên DB và quá nhiều concurrent query có thể tăng contention, context switching và queueing. Pool cần giới hạn theo capacity DB, số replica/app instance và workload; đặt timeout, release connection đúng cách và quan sát wait time. Tối ưu query/index, giảm transaction duration và kiểm soát concurrency thường quan trọng hơn tăng pool mù quáng.',
    'backend-engineer',
    'senior',
    ['postgresql'],
    4,
  ),
  technical(
    'sql-soft-delete-constraints',
    'Soft delete và unique constraint',
    'Nếu user đã “soft deleted”, làm sao cho phép dùng lại email mà vẫn giữ lịch sử?',
    'Cần định nghĩa semantic trước: email có được tái sử dụng hay không, audit/restore hoạt động thế nào. Nếu cho tái sử dụng, có thể dùng partial unique index chỉ áp dụng cho row active, ví dụ với deleted_at IS NULL, và mọi query phải mặc định lọc deleted row. Soft delete tăng độ phức tạp cho foreign key, GDPR/retention và index; không coi nó là giải pháp mặc định.',
    'backend-engineer',
    'senior',
    ['postgresql'],
    4,
  ),

  // System design
  technical(
    'system-design-url-shortener',
    'Thiết kế dịch vụ rút gọn URL',
    'Hãy thiết kế dịch vụ rút gọn URL có đọc nhiều hơn ghi. Trình bày assumptions, API, dữ liệu, scale và các trade-off.',
    'Khung trả lời: làm rõ QPS, độ bền, custom alias, TTL, analytics và tính nhất quán redirect. API tạo/redirect; mapping short code -> URL trong storage bền vững, cache cho hot key, ID/encoding tránh collision và uniqueness constraint. Thảo luận partitioning, cache invalidation, rate limit/chống abuse, observability và redirect availability. Không có một kiến trúc duy nhất; lựa chọn phụ thuộc workload và SLO.',
    'backend-engineer',
    'senior',
    ['redis', 'postgresql', 'rest-api'],
    5,
    'system_design',
  ),
  technical(
    'system-design-cache-stampede',
    'Ngăn cache stampede',
    'Một hot key hết TTL làm hàng nghìn request cùng truy vấn database. Bạn xử lý thế nào?',
    'Có thể dùng request coalescing/single-flight, lock ngắn có timeout, stale-while-revalidate, TTL jitter và prewarm có chọn lọc. Phải định nghĩa hành vi khi refresh fail, giới hạn concurrency và tránh lock distributed thiếu fencing/timeout. Cache là lớp tối ưu, nên database vẫn cần bảo vệ bằng rate/concurrency limit và capacity planning.',
    'backend-engineer',
    'senior',
    ['redis', 'nodejs'],
    5,
    'system_design',
  ),
  technical(
    'system-design-queue-delivery',
    'At-least-once delivery và idempotent consumer',
    'Vì sao consumer queue cần idempotency ngay cả khi broker nói “at-least-once”?',
    'At-least-once cho phép redelivery khi ack thất bại hoặc consumer crash sau side effect. Consumer phải xử lý duplicate bằng idempotency key/dedup store, unique constraint hoặc operation commutative, và chỉ ack khi side effect bền vững. Cần có retry phân loại, backoff, DLQ và observability; “exactly once” end-to-end không nên được khẳng định nếu side effect ngoài broker không chứng minh được.',
    'backend-engineer',
    'senior',
    ['kafka', 'rabbitmq', 'postgresql'],
    5,
    'system_design',
  ),
  technical(
    'system-design-outbox-pattern',
    'Outbox pattern giải quyết vấn đề gì?',
    'Sau khi ghi order vào DB rồi publish event, process chết ở giữa. Outbox pattern xử lý thế nào?',
    'Ghi domain change và outbox record trong cùng database transaction. Một relay đọc outbox, publish có retry/idempotency rồi đánh dấu trạng thái; consumer vẫn cần dedup vì publish có thể lặp. Pattern giảm dual-write inconsistency nhưng thêm độ trễ và vận hành relay/retention/monitoring. Cần phân biệt event schema version với domain model.',
    'backend-engineer',
    'senior',
    ['postgresql', 'kafka'],
    5,
    'system_design',
  ),
  technical(
    'system-design-file-upload',
    'Thiết kế upload file lớn',
    'Bạn thiết kế upload file lớn an toàn và có thể mở rộng như thế nào?',
    'Client nhận pre-signed upload hoặc session multipart từ backend sau authorization; file đi thẳng object storage thay vì qua API app. Enforce size/type/content policy, checksum khi phù hợp, scan malware bất đồng bộ trước khi file public, metadata ownership server-side và lifecycle cleanup có kiểm soát. Cần handle retry/resume, expiry URL, event duplicate và không tin Content-Type do client gửi.',
    'backend-engineer',
    'senior',
    ['aws', 'nodejs'],
    5,
    'system_design',
  ),
  technical(
    'system-design-observability-slo',
    'Định nghĩa SLI/SLO cho API',
    'Bạn chọn SLI và alert như thế nào để vừa phát hiện sự cố vừa tránh alert fatigue?',
    'Bắt đầu từ user journey quan trọng: ví dụ tỷ lệ request thành công và latency theo endpoint/region, có loại trừ rõ các request client-cancel hay không. Đặt SLO theo error budget, alert dựa trên burn rate nhiều cửa sổ thay vì mỗi spike nhỏ, và dashboard có traffic, dependency, saturation cùng trace/correlation ID. Metrics kỹ thuật như CPU hỗ trợ chẩn đoán nhưng không thay thế SLI trải nghiệm người dùng.',
    'devops-engineer',
    'senior',
    ['kubernetes', 'nodejs'],
    5,
    'system_design',
  ),
  technical(
    'system-design-multi-tenant-isolation',
    'Cô lập tenant trong SaaS',
    'Những lớp nào cần enforce tenant isolation ngoài việc thêm tenant_id vào bảng?',
    'Tenant context phải được xác thực từ identity, không từ body/query client; authorization và query repository cần scope tenant mặc định. Database constraint/index, row-level security khi phù hợp, cache key, object storage path, queue payload, search index và telemetry đều phải tránh cross-tenant leak. Cần test bằng tenant khác, audit admin access và có chiến lược migration/export/retention theo tenant.',
    'backend-engineer',
    'senior',
    ['postgresql', 'redis'],
    5,
    'system_design',
  ),
  technical(
    'system-design-api-versioning',
    'Versioning API không làm vỡ client',
    'Bạn thay đổi response field hoặc semantic API thế nào để client cũ vẫn hoạt động?',
    'Ưu tiên thay đổi additive và contract rõ ràng; không đổi nghĩa field âm thầm. Khi breaking change cần version/deprecation policy, timeline, telemetry usage và migration guide; version có thể ở path/header/media type tùy hệ sinh thái, quan trọng là nhất quán. Validate backward compatibility bằng contract tests và phối hợp release client/server.',
    'backend-engineer',
    'senior',
    ['rest-api', 'graphql'],
    4,
    'system_design',
  ),
  technical(
    'system-design-disaster-recovery',
    'RPO và RTO trong thiết kế dữ liệu',
    'RPO và RTO ảnh hưởng gì tới backup, replication và quy trình khôi phục?',
    'RPO là lượng dữ liệu chấp nhận mất theo thời gian; RTO là thời gian chấp nhận gián đoạn. Chúng phải được product/business xác nhận, rồi dẫn đến backup frequency, PITR, replication/failover và runbook. Backup chỉ đáng tin khi restore drill định kỳ chứng minh được thời gian, quyền truy cập, integrity và dependency cần thiết.',
    'cloud-solutions-architect',
    'senior',
    ['postgresql', 'aws'],
    5,
    'system_design',
  ),
  technical(
    'system-design-search-index-consistency',
    'Đồng bộ search index với database',
    'Khi search index bất đồng bộ với database, UX và kiến trúc cần xử lý gì?',
    'Chấp nhận eventual consistency một cách minh bạch nếu use case cho phép: write xác nhận dữ liệu nguồn trước, event/outbox cập nhật index, retry/dedup và monitor lag/failure. Search result cần re-check authorization và có thể fallback/read-after-write strategy cho màn hình vừa tạo. Không để index là source of truth cho invariant giao dịch nếu nó không có transaction semantics tương đương.',
    'backend-engineer',
    'senior',
    ['elasticsearch', 'postgresql', 'kafka'],
    5,
    'system_design',
  ),

  // Behavioral and HR
  framework(
    'behavioral-conflict-with-engineer',
    'Xử lý bất đồng kỹ thuật trong nhóm',
    'Hãy kể về một lần bạn không đồng ý với đồng đội về giải pháp kỹ thuật quan trọng. Bạn đã làm gì và kết quả ra sao?',
    'Dùng STAR: nêu quyết định và rủi ro liên quan; mô tả cách bạn lắng nghe tiêu chí của bên kia, thu thập dữ liệu/POC hoặc RFC, đưa trade-off ra thảo luận và chốt quyết định theo mục tiêu chung. Nêu đóng góp cá nhân, kết quả đo được và bài học về cách làm rõ decision owner sớm hơn.',
    'engineering-manager-tech-lead',
    'mid-level',
  ),
  framework(
    'behavioral-production-incident',
    'Ứng phó sự cố production',
    'Hãy kể về sự cố production mà bạn tham gia xử lý. Bạn cân bằng khôi phục dịch vụ và điều tra nguyên nhân như thế nào?',
    'Dùng STAR: mô tả tác động bằng dữ liệu, vai trò on-call/incident role của bạn và các hành động giảm ảnh hưởng trước. Giải thích cách phối hợp, giao tiếp stakeholder, dùng metric/log/rollback để đưa hệ thống về trạng thái an toàn, rồi phân tích nguyên nhân không đổ lỗi và theo dõi action item đến khi hoàn thành.',
    'backend-engineer',
    'mid-level',
  ),
  framework(
    'behavioral-feedback-received',
    'Phản hồi khó tiếp nhận',
    'Hãy kể về phản hồi khó tiếp nhận mà bạn đã nhận và cách bạn thay đổi sau đó.',
    'Dùng STAR: nêu bối cảnh không hạ thấp người đưa phản hồi; diễn giải điều bạn đã hỏi để hiểu kỳ vọng, hành động thay đổi cụ thể và cách đo tiến bộ. Kết thúc bằng tác động thực tế cùng điều bạn vẫn đang tiếp tục cải thiện. Một câu trả lời tốt thể hiện ownership, không phòng thủ và không biến feedback thành lỗi của người khác.',
    'frontend-engineer',
    'junior',
    2,
  ),
  framework(
    'behavioral-ambiguous-requirements',
    'Làm việc với yêu cầu mơ hồ',
    'Hãy kể về lần bạn phải triển khai khi yêu cầu chưa rõ ràng. Bạn đã giảm rủi ro như thế nào?',
    'Dùng STAR: phân tách điều đã biết/chưa biết, xác định stakeholder và impact của từng giả định. Mô tả việc viết câu hỏi, đề xuất option kèm trade-off, chia nhỏ delivery/feature flag hoặc prototype để học nhanh, và cách cập nhật quyết định khi có thông tin mới. Không mô tả “tự đoán rồi làm” như một thành công.',
    'fullstack-engineer',
    'mid-level',
  ),
  framework(
    'behavioral-mentoring',
    'Mentoring thành viên mới',
    'Bạn đã giúp một đồng đội phát triển năng lực như thế nào mà không biến mình thành điểm nghẽn?',
    'Dùng STAR: nêu gap cụ thể và mục tiêu học, đưa hỗ trợ theo cấp độ như pairing, review có tiêu chí, tài liệu hoặc ownership tăng dần. Mô tả cách bạn để người được mentoring tự ra quyết định, phản hồi đều đặn và đo kết quả qua chất lượng/độc lập, thay vì chỉ kể số giờ hướng dẫn.',
    'engineering-manager-tech-lead',
    'senior',
  ),
  framework(
    'behavioral-prioritization',
    'Ưu tiên khi có nhiều việc gấp',
    'Kể về lần bạn phải chọn giữa sửa lỗi, tính năng mới và technical debt. Bạn ra quyết định thế nào?',
    'Dùng STAR: nêu các lựa chọn, tác động khách hàng/rủi ro và deadline. Giải thích framework ưu tiên (severity, blast radius, cost of delay, compliance), ai tham gia quyết định, phần việc được hoãn có ghi nhận rủi ro hay không và kết quả. Câu trả lời tốt không nói “luôn ưu tiên deadline” hoặc “luôn refactor trước”.',
    'backend-engineer',
    'mid-level',
  ),
  framework(
    'behavioral-failure-learning',
    'Thất bại và bài học',
    'Hãy kể về một quyết định kỹ thuật không đạt kết quả như mong đợi. Bạn chịu trách nhiệm và cải thiện thế nào?',
    'Dùng STAR: mô tả mục tiêu ban đầu, tín hiệu cảnh báo đã bỏ lỡ hoặc giả định sai, trách nhiệm của bản thân và hành động khắc phục. Trình bày cơ chế phòng ngừa như guardrail, test, design review, rollout hoặc monitoring; không đổ lỗi, không tiết lộ thông tin mật và không giả vờ thất bại không có hậu quả.',
    'backend-engineer',
    'mid-level',
  ),
  framework(
    'behavioral-influence-without-authority',
    'Thuyết phục khi không có quyền quyết định',
    'Bạn đã ảnh hưởng một quyết định liên phòng ban mà không có quyền quản lý trực tiếp như thế nào?',
    'Dùng STAR: xác định mục tiêu chung và stakeholder, tìm hiểu constraint của từng bên, đưa bằng chứng/option thay vì ép buộc và tạo không gian phản biện. Nêu cách bạn chấp nhận decision cuối cùng, giao tiếp rõ ràng và đo tác động. Tránh kể theo hướng “tôi thắng tranh luận”.',
    'engineering-manager-tech-lead',
    'senior',
  ),
  framework(
    'hr-self-introduction-engineer',
    'Giới thiệu bản thân cho vị trí kỹ sư phần mềm',
    'Hãy giới thiệu bản thân trong khoảng 90 giây cho một buổi phỏng vấn Backend Engineer.',
    'Khung trả lời: mở bằng vai trò hiện tại và số năm kinh nghiệm phù hợp; chọn 1–2 thành tựu liên quan trực tiếp đến backend với bối cảnh, hành động và tác động có thể giải thích; liên kết với lý do ứng tuyển và loại vấn đề bạn muốn giải quyết. Giữ trung thực, không đọc lại toàn bộ CV và tránh liệt kê công nghệ không kèm mức độ sử dụng.',
    'backend-engineer',
    'junior',
    2,
  ),
  framework(
    'hr-career-motivation',
    'Động lực chuyển việc',
    'Bạn trả lời thế nào khi được hỏi “Vì sao bạn muốn chuyển việc vào lúc này?”',
    'Khung trả lời: nói tích cực và nhất quán về điều bạn đang tìm kiếm—phạm vi vấn đề, cơ hội học hỏi, trách nhiệm hoặc môi trường hợp tác—rồi liên hệ với vị trí. Có thể thừa nhận constraint thực tế một cách ngắn gọn nhưng không công kích công ty/đồng nghiệp cũ, không bịa lý do và không biến lương thành toàn bộ câu chuyện.',
    'fullstack-engineer',
    'junior',
    2,
  ),
  framework(
    'hr-career-goals',
    'Mục tiêu nghề nghiệp 2–3 năm',
    'Bạn trả lời câu hỏi về mục tiêu nghề nghiệp 2–3 năm thế nào để vừa cụ thể vừa không hứa quá mức?',
    'Khung trả lời: nêu năng lực và loại tác động bạn muốn xây dựng, ví dụ trở thành kỹ sư có thể sở hữu một mảng sản phẩm, nâng độ sâu về reliability hoặc hỗ trợ đồng đội. Liên hệ với cơ hội thực của vị trí và cho thấy bạn sẵn sàng học qua feedback. Tránh khẳng định chắc chắn một title/thăng chức hoặc đưa mục tiêu không liên quan công việc.',
    'frontend-engineer',
    'junior',
    2,
  ),
  framework(
    'hr-salary-expectations',
    'Trao đổi kỳ vọng lương chuyên nghiệp',
    'Bạn trả lời thế nào khi nhà tuyển dụng hỏi kỳ vọng lương ở vòng đầu?',
    'Khung trả lời: trước hết tìm hiểu phạm vi trách nhiệm, tổng đãi ngộ, location và level; nếu cần đưa số, nêu khoảng dựa trên nghiên cứu thị trường và mức phù hợp với kinh nghiệm, đồng thời nói rõ bạn muốn đánh giá tổng gói. Không cung cấp thông tin lương cũ nếu không muốn, không đe dọa và không đưa con số không thể giải thích.',
    'fullstack-engineer',
    'mid-level',
    3,
  ),
];
