export enum SessionState {
  CREATED = 'CREATED',
  ACTIVE = 'ACTIVE',
  EVALUATING = 'EVALUATING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum LearningPathStatus {
  PENDING = 'PENDING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum UserRole {
  CANDIDATE = 'CANDIDATE',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  LOCKED = 'LOCKED',
}

export enum DifficultyLevel {
  EASY = 1,
  MEDIUM = 2,
  HARD = 3,
}

export enum QueueName {
  QUESTION_GENERATION = 'question-generation',
  ANSWER_EVALUATION = 'answer-evaluation',
  LEARNING_PATH = 'learning-path',
}

export enum JobName {
  GENERATE_QUESTION = 'generate-question',
  EVALUATE_ANSWER = 'evaluate-answer',
  GENERATE_LEARNING_PATH = 'generate-learning-path',
}

export enum SseEventType {
  SESSION_UPDATED = 'session_updated',
  QUESTION_READY = 'question_ready',
  EVALUATION_COMPLETED = 'evaluation_completed',
  LEARNING_PATH_READY = 'learning_path_ready',
  SESSION_FAILED = 'session_failed',
  HEARTBEAT = 'heartbeat',
}

export enum AiRunStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum AuditAction {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOCKED = 'USER_LOCKED',
  USER_UNLOCKED = 'USER_UNLOCKED',
  SESSION_CREATED = 'SESSION_CREATED',
  ANSWER_SUBMITTED = 'ANSWER_SUBMITTED',
  EVALUATION_COMPLETED = 'EVALUATION_COMPLETED',
  LEARNING_PATH_GENERATED = 'LEARNING_PATH_GENERATED',
}

export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  USER_LOCKED = 'USER_LOCKED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  MAX_TURNS_REACHED = 'MAX_TURNS_REACHED',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  ANSWER_ALREADY_ACCEPTED = 'ANSWER_ALREADY_ACCEPTED',
  AI_GENERATION_FAILED = 'AI_GENERATION_FAILED',
  AI_EVALUATION_FAILED = 'AI_EVALUATION_FAILED',
  AI_SCHEMA_INVALID = 'AI_SCHEMA_INVALID',
  AI_TIMEOUT = 'AI_TIMEOUT',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  SELF_LOCK_FORBIDDEN = 'SELF_LOCK_FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
