export enum SessionState {
  CREATED = 'CREATED',
  ACTIVE = 'ACTIVE',
  EVALUATING = 'EVALUATING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum LearningPathStatus {
  PENDING = 'PENDING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum UserRole {
  CANDIDATE = 'CANDIDATE',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  LOCKED = 'LOCKED',
}

export enum DifficultyLevel {
  EASY = 1,
  MEDIUM = 2,
  HARD = 3,
}

export enum QueueName {
  QUESTION_GENERATION = 'question-generation',
  ANSWER_EVALUATION = 'answer-evaluation',
  LEARNING_PATH = 'learning-path',
  EMAIL = 'email',
}

export enum JobName {
  GENERATE_QUESTION = 'generate-question',
  EVALUATE_ANSWER = 'evaluate-answer',
  GENERATE_LEARNING_PATH = 'generate-learning-path',
  SEND_EMAIL = 'send-email',
}

export enum SseEventType {
  SESSION_UPDATED = 'session_updated',
  QUESTION_READY = 'question_ready',
  EVALUATION_COMPLETED = 'evaluation_completed',
  LEARNING_PATH_READY = 'learning_path_ready',
  SESSION_FAILED = 'session_failed',
  HEARTBEAT = 'heartbeat',
}

export enum AiRunStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum InterviewMode {
  TEXT = 'TEXT',
  VOICE = 'VOICE',
}

export enum AudioProvider {
  OPENAI = 'OPENAI',
  GROQ = 'GROQ',
  ELEVENLABS = 'ELEVENLABS',
  BROWSER_NATIVE = 'BROWSER_NATIVE',
  MOCK = 'MOCK',
}

export enum AudioVoice {
  ALLOY = 'alloy',
  ECHO = 'echo',
  FABLE = 'fable',
  ONYX = 'onyx',
  NOVA = 'nova',
  SHIMMER = 'shimmer',
}

export enum TranscriptionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum CompetencyArea {
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
  LANGUAGE_CORE = 'LANGUAGE_CORE',
  DATABASE_CONCURRENCY = 'DATABASE_CONCURRENCY',
  ARCHITECTURE_PATTERNS = 'ARCHITECTURE_PATTERNS',
  RESILIENCE_SECURITY = 'RESILIENCE_SECURITY',
}

export enum ShareExpiryDuration {
  ONE_DAY = '1d',
  SEVEN_DAYS = '7d',
  THIRTY_DAYS = '30d',
  NEVER = 'never',
}

export enum SessionMode {
  STANDARD = 'STANDARD',
  FOCUSED_REMEDIATION = 'FOCUSED_REMEDIATION',
  QUICK_PRACTICE = 'QUICK_PRACTICE',
  CODING = 'CODING',
  BEHAVIORAL = 'BEHAVIORAL',
  VOICE_LIVE = 'VOICE_LIVE',
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
}

export enum TutorRole {
  USER = 'USER',
  AI_TUTOR = 'AI_TUTOR',
  SYSTEM = 'SYSTEM',
}

export enum CardType {
  CONCEPT = 'CONCEPT',
  CODE_SNIPPET = 'CODE_SNIPPET',
  SCENARIO = 'SCENARIO',
  MCQ = 'MCQ',
}

export enum CardState {
  NEW = 'NEW',
  LEARNING = 'LEARNING',
  REVIEW = 'REVIEW',
  RELEARNING = 'RELEARNING',
}

export enum FSRSRating {
  AGAIN = 1,
  HARD = 2,
  GOOD = 3,
  EASY = 4,
}

export enum VoiceSessionStatus {
  CONNECTING = 'CONNECTING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum SpeakerRole {
  USER = 'USER',
  AI = 'AI',
}

export const VoiceEventType = {
  // Client -> Server
  CONNECT: 'voice:connect',
  AUDIO_CHUNK: 'voice:audio_chunk',
  INTERRUPT: 'voice:interrupt',
  MUTE_TOGGLE: 'voice:mute_toggle',
  DISCONNECT: 'voice:disconnect',

  // Server -> Client
  CONNECTED: 'voice:connected',
  INTERIM_TRANSCRIPT: 'voice:interim_transcript',
  FINAL_TRANSCRIPT: 'voice:final_transcript',
  AI_AUDIO_CHUNK: 'voice:ai_audio_chunk',
  AI_SPEAKING_START: 'voice:ai_speaking_start',
  AI_SPEAKING_END: 'voice:ai_speaking_end',
  CONNECTION_QUALITY: 'voice:connection_quality',
  ERROR: 'voice:error',
  FALLBACK_TO_TEXT: 'voice:fallback_to_text',
} as const;

export type VoiceEventType = (typeof VoiceEventType)[keyof typeof VoiceEventType];

export enum SubmissionStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  COMPILE_ERROR = 'COMPILE_ERROR',
  TIMEOUT = 'TIMEOUT',
}

export enum BehavioralCategory {
  LEADERSHIP = 'LEADERSHIP',
  TEAMWORK = 'TEAMWORK',
  PROBLEM_SOLVING = 'PROBLEM_SOLVING',
  COMMUNICATION = 'COMMUNICATION',
  ADAPTABILITY = 'ADAPTABILITY',
}

export enum SubscriptionStatus {
  TRIALING = 'TRIALING',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELED = 'CANCELED',
  UNPAID = 'UNPAID',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  PAID = 'PAID',
  VOID = 'VOID',
  UNCOLLECTIBLE = 'UNCOLLECTIBLE',
}

export enum BillingMetric {
  AI_TOKEN = 'AI_TOKEN',
  AUDIO_MINUTE = 'AUDIO_MINUTE',
  SESSION_COUNT = 'SESSION_COUNT',
}

export enum AuditAction {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOCKED = 'USER_LOCKED',
  USER_UNLOCKED = 'USER_UNLOCKED',
  SESSION_CREATED = 'SESSION_CREATED',
  ANSWER_SUBMITTED = 'ANSWER_SUBMITTED',
  EVALUATION_COMPLETED = 'EVALUATION_COMPLETED',
  EVALUATION_RE_EVALUATED = 'EVALUATION_RE_EVALUATED',
  LEARNING_PATH_GENERATED = 'LEARNING_PATH_GENERATED',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
  PROMPT_VERSION_ACTIVATED = 'PROMPT_VERSION_ACTIVATED',
  AUDIO_TRANSCRIPTION_REQUESTED = 'AUDIO_TRANSCRIPTION_REQUESTED',
  AUDIO_SYNTHESIS_REQUESTED = 'AUDIO_SYNTHESIS_REQUESTED',
  VOICE_MODE_TOGGLED = 'VOICE_MODE_TOGGLED',
  SHARE_LINK_CREATED = 'SHARE_LINK_CREATED',
  SHARE_LINK_REVOKED = 'SHARE_LINK_REVOKED',
  MENTOR_FEEDBACK_SUBMITTED = 'MENTOR_FEEDBACK_SUBMITTED',
  SESSION_DATA_EXPORTED = 'SESSION_DATA_EXPORTED',
  LEARNING_GOAL_TOGGLED = 'LEARNING_GOAL_TOGGLED',
  REMEDIATION_SESSION_STARTED = 'REMEDIATION_SESSION_STARTED',
  MFA_SETUP_INITIATED = 'MFA_SETUP_INITIATED',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_VERIFIED = 'MFA_VERIFIED',
  MFA_RECOVERY_USED = 'MFA_RECOVERY_USED',
  MFA_DISABLED = 'MFA_DISABLED',
  CODE_EXECUTED = 'CODE_EXECUTED',
  CODE_SUBMITTED = 'CODE_SUBMITTED',
  STAR_EVALUATED = 'STAR_EVALUATED',
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED = 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED',
  INVOICE_PAID = 'INVOICE_PAID',
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DELETED = 'FILE_DELETED',
  PAYMENT_LINK_CREATED = 'PAYMENT_LINK_CREATED',
  PAYOS_WEBHOOK_RECEIVED = 'PAYOS_WEBHOOK_RECEIVED',
  DIAGRAM_EVALUATED = 'DIAGRAM_EVALUATED',
  EMAIL_DISPATCHED = 'EMAIL_DISPATCHED',
}

export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  USER_LOCKED = 'USER_LOCKED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  MAX_TURNS_REACHED = 'MAX_TURNS_REACHED',
  QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
  ANSWER_ALREADY_ACCEPTED = 'ANSWER_ALREADY_ACCEPTED',
  AI_GENERATION_FAILED = 'AI_GENERATION_FAILED',
  AI_EVALUATION_FAILED = 'AI_EVALUATION_FAILED',
  AI_SCHEMA_INVALID = 'AI_SCHEMA_INVALID',
  AI_TIMEOUT = 'AI_TIMEOUT',
  AUDIO_RECORDING_FAILED = 'AUDIO_RECORDING_FAILED',
  AUDIO_TRANSCRIPTION_FAILED = 'AUDIO_TRANSCRIPTION_FAILED',
  AUDIO_SYNTHESIS_FAILED = 'AUDIO_SYNTHESIS_FAILED',
  AUDIO_PAYLOAD_TOO_LARGE = 'AUDIO_PAYLOAD_TOO_LARGE',
  AUDIO_UNSUPPORTED_FORMAT = 'AUDIO_UNSUPPORTED_FORMAT',
  MICROPHONE_PERMISSION_DENIED = 'MICROPHONE_PERMISSION_DENIED',
  SHARE_LINK_NOT_FOUND = 'SHARE_LINK_NOT_FOUND',
  SHARE_LINK_EXPIRED = 'SHARE_LINK_EXPIRED',
  SHARE_LINK_REVOKED = 'SHARE_LINK_REVOKED',
  MFA_REQUIRED = 'MFA_REQUIRED',
  MFA_INVALID_CODE = 'MFA_INVALID_CODE',
  MFA_ALREADY_ENABLED = 'MFA_ALREADY_ENABLED',
  MFA_NOT_ENABLED = 'MFA_NOT_ENABLED',
  MFA_INVALID_SESSION = 'MFA_INVALID_SESSION',
  MFA_STEP_UP_REQUIRED = 'MFA_STEP_UP_REQUIRED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  SELF_LOCK_FORBIDDEN = 'SELF_LOCK_FORBIDDEN',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
  SUBSCRIPTION_REQUIRED = 'SUBSCRIPTION_REQUIRED',
  CODE_EXECUTION_FAILED = 'CODE_EXECUTION_FAILED',
  CODE_EXECUTION_TIMEOUT = 'CODE_EXECUTION_TIMEOUT',
  INVALID_LANGUAGE = 'INVALID_LANGUAGE',
  WEBHOOK_SIGNATURE_INVALID = 'WEBHOOK_SIGNATURE_INVALID',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum BadgeLevel {
  BRONZE = 'BRONZE',
  SILVER = 'SILVER',
  GOLD = 'GOLD',
  PLATINUM = 'PLATINUM',
}

export enum CertificateStatus {
  GENERATING = 'GENERATING',
  ISSUED = 'ISSUED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
}

export enum LiveSessionStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
}

export enum TenantRole {
  TENANT_ADMIN = 'TENANT_ADMIN',
  INSTRUCTOR = 'INSTRUCTOR',
  STUDENT = 'STUDENT',
}

export enum AssignmentStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  CLOSED = 'CLOSED',
}

export enum XpSource {
  INTERVIEW_COMPLETE = 'INTERVIEW_COMPLETE',
  FLASHCARD_REVIEW = 'FLASHCARD_REVIEW',
  CODING_SUBMIT = 'CODING_SUBMIT',
  STAR_COMPLETE = 'STAR_COMPLETE',
  STREAK_BONUS = 'STREAK_BONUS',
  BADGE_UNLOCK = 'BADGE_UNLOCK',
  DAILY_LOGIN = 'DAILY_LOGIN',
}

